language: php

env:
  global:
    - GLPI_SOURCE="https://github.com/glpi-project/glpi"
    - PHPUNIT_ARGS="--verbose --debug"
    - CS=7.2
  matrix:
    - GLPI_BRANCH=9.2.1
    - GLPI_BRANCH=9.2/bugfixes
    - GLPI_BRANCH=9.3/bugfixes
    - GLPI_BRANCH=master

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

allow_failures:
  - php: nightly
  - env: GLPI_BRANCH=master

addons:
  firefox: "latest-esr"

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  
before_script:
  - mysql -u root -e 'create database glpitest;'
  - git clone --depth=1 $GLPI_SOURCE -b $GLPI_BRANCH ../glpi && cd ../glpi
  - mv ../formcreator plugins/formcreator
  - composer install --no-dev
  - if [ -e scripts/cliinstall.php ] ; then php scripts/cliinstall.php --db=glpitest --user=root --tests ; fi
  - if [ -e tools/cliinstall.php ] ; then php tools/cliinstall.php --db=glpitest --user=root --tests ; fi
  - cd plugins/formcreator
  - rm composer.lock
  - composer install
  - npm install -g phantomjs-prebuilt
  - npm install -g casperjs
  - npm install -g slimerjs
  - php -S localhost:8088 --docroot ../.. ../../tests/router.php &>/dev/null &
  - mysql --version
  - casperjs --version

script:
  - vendor/bin/phpunit $PHPUNIT_ARGS --testsuite Install
  - vendor/bin/phpunit $PHPUNIT_ARGS --testsuite Unit
  - vendor/bin/phpunit $PHPUNIT_ARGS --testsuite Integration
  - mysql -u root $DB < save.sql
  - casperjs test tests/0020_Functional/*Test.js --engine=phantomjs
  - mysql -u root $DB < save.sql
  - casperjs test tests/0020_Functional/*Test.js --engine=slimerjs
  - vendor/bin/phpunit $PHPUNIT_ARGS --testsuite Uninstall
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "$CS" ]] ; then vendor/bin/robo --no-interaction code:cs; fi

cache:
  directories:
    - $HOME/.composer/cache
