language: php

env:
  global:
    - GLPI_SOURCE="https://github.com/glpi-project/glpi -b 9.2/bugfixes" 
    - PHPUNIT_ARGS="--verbose --debug"

before_script:
  - mysql -u root -e 'create database glpitest;'
  - git clone https://github.com/glpi-project/glpi --depth 1 -b 9.2/bugfixes ../glpi && cd ../glpi
  - mv ../formcreator plugins/formcreator
  - composer install --no-dev
  - php tools/cliinstall.php --db=glpitest --user=root --tests
  - cd plugins/formcreator
  - rm composer.lock
  - composer install

script:
  - vendor/bin/phpunit $PHPUNIT_ARGS
  - if [[ "$CS" == "true" ]]; then vendor/bin/robo --no-interaction code:cs; fi

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
      env: CS=true
    - php: nightly

  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
